# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-13 01:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortener', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='short_url',
            field=models.CharField(max_length=100, unique=True, verbose_name='shortened URL'),
        ),
    ]
