# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-13 02:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortener', '0003_auto_20170912_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
