# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 00:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('short_desc', models.CharField(max_length=140)),
                ('long_desc', models.TextField()),
                ('git_link', models.URLField(verbose_name='Github URL')),
                ('live_link', models.URLField(verbose_name='Live URL')),
                ('order_int', models.IntegerField(default=0)),
            ],
        ),
    ]
