# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 00:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='tech_used',
            field=models.CharField(default='', max_length=140, verbose_name='Technology Used'),
        ),
        migrations.AlterField(
            model_name='project',
            name='long_desc',
            field=models.TextField(verbose_name='Long Description'),
        ),
        migrations.AlterField(
            model_name='project',
            name='short_desc',
            field=models.CharField(max_length=140, verbose_name='Short Description'),
        ),
    ]
