# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 00:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0002_auto_20170926_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='git_link',
            field=models.URLField(blank=True, verbose_name='Github URL'),
        ),
        migrations.AlterField(
            model_name='project',
            name='live_link',
            field=models.URLField(blank=True, verbose_name='Live URL'),
        ),
    ]
