# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 00:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0003_auto_20170926_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='img_link',
            field=models.URLField(blank=True, verbose_name='Image Link'),
        ),
    ]
