# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 01:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0004_project_img_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='order_int',
            field=models.IntegerField(default=0, verbose_name='Order (lower is ranked higher)'),
        ),
    ]
